spring:
  application:
    name: ${APP_NAME}
  data:
    mongodb:
      uri: ${MONGO_URI}

jwt:
  secret: ${JWT_SECRET}
  
cron:
  exp:
    remusers: ${REM_USERS_CRON_EXP}
    
verify:
  email: ${VERIFY_EMAIL}